//Where is DB located? Connection string tells you.
spring.datasource.url = jdbc:postgresql:localhost:5432/questions
spring.datasource.username=postgresql 
spring.datasource.password=

spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.format_sql = true