name: BackEnd Workflow

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Java
              uses: actions/setup-java@v5
              with:
                distribution: 'temurin'
                java-version: '17'
                cache: 'maven'
            - name: Build application
              run: mvn clean package -DskipTests #Skipping the Smoke Test
            - name: Docker Hub Login
              uses: docker/login-action@v3
            - name: Build Docker Compose image
              run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/sundar-backend:latest
            - name: Push to Docker Hub
              run: docker push ${{secrets.DOCKERHUB_USERNAME}}/sundar-backend:latest
    
    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Deploy to EC2
              uses: appleboy/ssh-action@v1.2.2
              with: 
                host: ${{secrets.EC2_HOST}}
                username: ${{secrets.EC2_USERNAME}}
                key: ${{secrets.EC2_SSH_KEY}}
                script: |
                  cd /home/ec2-user/sundar-backend
                  docker compose pull
                  docker compose up -d
                
            
           