name: BackEnd Workflow

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Java
              uses: actions/setup-java@v5
              with:
                distribution: 'temurin'
                java-version: '17'
                cache: 'maven'
            - name: Build application
              run: mvn clean package -DskipTests #Skipping the Smoke Test
            - name: Docker Hub Login
              uses: docker/login-action@v4
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
            - name: Build Docker Image
              run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/sundar-backend:latest .
            - name: Push Docker Image
              run: docker push ${{secrets.DOCKERHUB_USERNAME}}/sundar-backend:latest