name: BackEnd Workflow

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Java
              uses: actions/setup-java@v5
              with:
                distribution: 'temurin'
                java-version: '17'
                cache: 'maven'
            - name: Build application
              run: mvn package
            - name: Build Container
              run: docker build -t image .
            - name: Run Container
              run: docker run -p 8081:8080 image
